#!/bin/bash -e

HERE=`dirname ${0}`
cd "${HERE}/.."
PROJECT=`pwd`
	RUN="${PROJECT}/run"
	TMP="/tmp"
		BUILDING="${TMP}/build_testory"
			UNPACKED="${BUILDING}/unpacked"
	MAIN="${PROJECT}/main"
		JAVA="${MAIN}/java"
		JAR="${MAIN}/jar"

########## CLEANUP ##########
rm \
  --recursive \
  --force \
  ${BUILDING}

mkdir \
  --parents \
  ${BUILDING}

mkdir \
  --parents \
  ${UNPACKED}

########## COMPILE SOURCES ##########
javac \
  -classpath "${JAR}/cglib-nodep-2.2.3.jar:${JAR}/objenesis-2.0.jar" \
  -sourcepath "${JAVA}" \
  -source 1.7 \
  -target 1.7 \
  -d "${UNPACKED}" \
  "${JAVA}/org/testory/Build.java"

########## COPY SOURCES ##########
cp \
  --recursive \
  "${JAVA}/." \
  "${UNPACKED}"

########## COPY DEPENDENCIES ##########
unzip \
  -q \
  "${JAR}/cglib-nodep-2.2.3.jar" \
  -d "${UNPACKED}" \
  net/*
unzip \
  -q \
  "${JAR}/objenesis-2.0.jar" \
  -d "${UNPACKED}" \
  org/*

########## COPY LICENSE FILES ##########
cp \
  --recursive \
  "${RUN}/license/." \
  "${UNPACKED}"

########## RESET TIMESTAMPS ##########
find \
  ${UNPACKED} \
| xargs \
touch \
  --date=@0

########## ZIP JAR ##########
cd ${UNPACKED}
zip \
  --quiet \
  --recurse-paths \
  ./testory.jar \
  ./*
cd "${PROJECT}"

########## INLINE DEPENDENCIES ##########
java \
  -jar "${RUN}/jarjar-1.4.jar" \
  process "${RUN}/jarjar-rules.txt" \
  "${UNPACKED}/testory.jar" \
  "${UNPACKED}/testory.jar"

########## COPY PRODUCED JAR ##########
cp \
  "${UNPACKED}/testory.jar" \
  "${BUILDING}"

########## CLEANUP ##########
rm \
  --recursive \
  --force \
  "${UNPACKED}"

echo ""
echo "BUILD SUCCESSFUL"
echo "created ${BUILDING}/testory.jar"
echo "sha1sum=`sha1sum ${BUILDING}/testory.jar | cut -f1 -d' '`"


