#!/bin/bash -e

HERE=`dirname ${0}`
cd "${HERE}/.."
PROJECT=`pwd`
	RUN="${PROJECT}/run"
	TMP="/tmp"
		BUILDING="${TMP}/build_testory"
			UNPACKED="${BUILDING}/unpacked"
	MAIN="${PROJECT}/main"
		JAVA="${MAIN}/java"
		JAR="${MAIN}/jar"

	JMODS="/usr/lib/jvm/default/jmods"

########## CLEANUP ##########
rm \
  --recursive \
  --force \
  ${BUILDING}

mkdir \
  --parents \
  ${BUILDING}

mkdir \
  --parents \
  ${UNPACKED}

########## COMPILE SOURCES ##########
javac \
  -classpath "${JAR}/cglib-nodep-3.3.0.jar:${JAR}/objenesis-3.3.jar" \
  -sourcepath "${JAVA}" \
  -source 1.8 \
  -target 1.8 \
  -d "${UNPACKED}" \
  "${JAVA}/org/testory/Build.java"

########## COPY SOURCES ##########
cp \
  --recursive \
  "${JAVA}/." \
  "${UNPACKED}"

########## COPY DEPENDENCIES ##########
unzip \
  -q \
  "${JAR}/cglib-nodep-3.3.0.jar" \
  -d "${UNPACKED}" \
  net/*
unzip \
  -q \
  "${JAR}/objenesis-3.3.jar" \
  -d "${UNPACKED}" \
  org/*

########## COPY LICENSE FILES ##########
cp \
  --recursive \
  "${RUN}/license/." \
  "${UNPACKED}"

########## RESET TIMESTAMPS ##########
find \
  ${UNPACKED} \
| xargs \
touch \
  --date=@0

########## ZIP JAR ##########
cd ${UNPACKED}
zip \
  --quiet \
  --recurse-paths \
  ${BUILDING}/testory.jar \
  ./*
cd "${PROJECT}"
rm -rf ${UNPACKED}

########## SHADE DEPENDENCIES ##########
jar tf ${BUILDING}/testory.jar \
  | grep "\.class$" \
  | grep -v "$org/testory/" \
  | sed 's/\.class$//g' \
  | sed  's/\//\./g' \
  | xargs -I{} echo {} -\> org.testory.shaded.{} : \
  > "${BUILDING}/shading_map.txt"


java \
  -cp "${RUN}/proguard-7.4.0.jar" \
  proguard.ProGuard \
  -injars "${BUILDING}/testory.jar" \
  -outjars "${BUILDING}/testory-shaded.jar" \
  -libraryjars "${JMODS}/java.base.jmod(!**.jar;!module-info.class)" \
  -libraryjars "${JMODS}/java.desktop.jmod" \
  -libraryjars "${JMODS}/jdk.unsupported.jmod" \
  -dontnote org.objenesis.** \
  -dontwarn net.sf.cglib.** \
  -dontnote net.sf.cglib.** \
  -dontshrink \
  -dontoptimize \
  -keepattributes \* \
  -keepparameternames \
  -keepclassmembers class \* { \
   \*\*\* \*\; \
   \*\*\* \*\(...\)\; \
  } \
  -keep class org.testory.** \
  -applymapping "${BUILDING}/shading_map.txt"

mv "${BUILDING}/testory-shaded.jar" "${BUILDING}/testory.jar"

rm "${BUILDING}/shading_map.txt"

########## RESET TIMESTAMPS IN JAR ##########
mkdir "${UNPACKED}"
unzip \
  -q \
  -d "${UNPACKED}" \
  "${BUILDING}/testory.jar"
find "${UNPACKED}" | xargs touch --date=@0
cd "${UNPACKED}"
zip \
  --quiet \
  -X \
  --recurse-paths \
  "${BUILDING}/testory.jar" \
  ./*
cd "${PROJECT}"
rm \
  --recursive \
  --force \
  "${UNPACKED}"

########## REPORT ##########

echo ""
echo "BUILD SUCCESSFUL"
echo "created ${BUILDING}/testory.jar"
echo "sha1sum=`sha1sum ${BUILDING}/testory.jar | cut -f1 -d' '`"


